Maps
tjncgit/STEP2020 pull request #11
Opened 2020-06-14 20:40 UTC by tjncgit

Uses Google Maps JavaScript API  to display a map on portfolio page

2020-06-15 11:43 UTC, Howon requested changes

2020-06-15 11:43 UTC, Howon commented on portfolio/pom.xml
> +          <deploy.projectId>hwb-interns-2020</deploy.projectId>
do we want to change this?

2020-06-15 11:43 UTC, Howon commented on portfolio/src/main/java/com/google/sps/servlets/DataServlet.java
> +      comments.add(email + ":\n" + "\n  " + comment);
you can just write `:\n\n `
Even better, you can use String.format
```
comments.add(String.format("%s\n\n %s", email, comment));
```

2020-06-15 11:43 UTC, Howon commented on portfolio/src/main/java/com/google/sps/servlets/DataServlet.java
> +    DatastoreService datastore = DatastoreServiceFactory.getDatastoreService();
as commented before, let's add this as a class variablelike you have in line 41 for `comments`

2020-06-15 11:43 UTC, Howon commented on portfolio/src/main/java/com/google/sps/servlets/DataServlet.java
> +       maxComments = Integer.parseInt(maxCommentsString);
indentation

2020-06-15 11:43 UTC, Howon commented on portfolio/src/main/java/com/google/sps/servlets/LoginStatus.java
> +        response.setContentType("text/html");
Please address https://github.com/tjncgit/STEP2020/pull/9. I commented that we should use a map or something

2020-06-15 11:43 UTC, Howon commented on portfolio/src/main/webapp/script.js
> +        console.log(type_value);
indentation

2020-06-15 11:43 UTC, Howon commented on portfolio/src/main/webapp/script.js
> +        console.log(type_value);
indentation

2020-06-15 16:50 UTC, tjncgit commented on portfolio/pom.xml
> +          <deploy.projectId>hwb-interns-2020</deploy.projectId>
I am using tamajongnc-step-2020

2020-06-22 18:22 UTC, Howon requested changes

2020-06-22 18:22 UTC, Howon commented on portfolio/src/main/java/com/google/sps/servlets/DataServlet.java
> +    DatastoreService datastore = DatastoreServiceFactory.getDatastoreService();
You shouldn't need this anymore right? since we have a datastore class variable

2020-06-22 18:22 UTC, Howon commented on portfolio/src/main/java/com/google/sps/servlets/LoginStatus.java
> +        }
please use spaces 

```java
if () {
} else {
}
```

2020-06-22 18:22 UTC, Howon commented on portfolio/src/main/java/com/google/sps/servlets/LoginStatus.java
> +        response.getWriter().println(loginStatus);
Why are you still using loginStatus? shouldn't this be a per-user login status that youa re using `userLoginBool` for?

2020-06-22 18:22 UTC, Howon commented on portfolio/src/main/java/com/google/sps/servlets/Logout.java
> +            response.sendRedirect(logoutUrl);
spaces 

```java
if () {
} else {
}
```

2020-06-22 18:22 UTC, Howon commented on portfolio/src/main/java/com/google/sps/servlets/Users.java
> +    //   response.getWriter().println("<p>Login <a href=\"" + loginUrl + "\">here</a>.</p>");
remove comments

2020-06-22 18:22 UTC, Howon commented on portfolio/src/main/java/com/google/sps/servlets/Users.java
> +    }
indentation

2020-06-22 18:22 UTC, Howon commented on portfolio/src/main/webapp/script.js
> +            link = document.getElementById("anchor");
Please format your code and use correct indentations

if () {
  for () {
  }
}

2020-06-22 18:22 UTC, Howon commented on portfolio/src/main/webapp/script.js
> +  });
please use a loop for this instead of copying it 4 times.

2020-06-23 03:34 UTC, Howon requested changes

2020-06-23 03:34 UTC, Howon commented on portfolio/src/main/java/com/google/sps/servlets/LoginStatus.java
> +            statusBool = userLoginBool.get(userEmail);
do we really want this as a class-wide variable? I am not sure why you want to do that. Isnt someone's login-status specific to the scope of this method?

What I am saying is, let's just declare this inside this doGet method

```java
public void doGet() {
  bool statusBool = false;
  if (user is logged in) {
    bool statusBool = true;
  }

  response.getWriter().println(statusbool);
}
```

This way, you don't even need the `if` branch

2020-06-23 19:32 UTC, tjncgit commented on portfolio/pom.xml
> +          <deploy.projectId>hwb-interns-2020</deploy.projectId>
idk why the diff isn't showing but when you look at the actual file i am using tamajongnc-step-2020

2020-06-24 02:11 UTC, Howon requested changes

2020-06-24 02:11 UTC, Howon commented on portfolio/src/main/java/com/google/sps/servlets/LoginStatus.java
>              boolean statusBool = userLoginBool.get(userEmail);
Shouldn't you declare this outside of this if?

2020-06-24 02:11 UTC, Howon commented on portfolio/src/main/java/com/google/sps/servlets/DataServlet.java
> +    }
indentation

2020-06-24 02:11 UTC, Howon commented on portfolio/src/main/java/com/google/sps/servlets/LoginStatus.java
> +  Map<String, Boolean> userLoginBool = new HashMap<String, Boolean>();
is this private or public?

2020-06-24 02:11 UTC, Howon commented on portfolio/src/main/java/com/google/sps/servlets/Users.java
> +    }
indentation

2020-06-24 02:11 UTC, Howon commented on portfolio/src/main/webapp/script.js
> +
remove console logs when committing

2020-06-24 02:11 UTC, Howon commented on portfolio/src/main/webapp/script.js
> +     param2 = document.getElementById('param2').value;
indentation

2020-06-24 02:11 UTC, Howon commented on portfolio/src/main/webapp/script.js
> +    let param1 = document.getElementById('param1').value,
we aren't changing it; why dont you use `const` here?

2020-06-24 02:11 UTC, Howon commented on portfolio/src/main/webapp/script.js
> +      "Japan is an island country in East Asia located in the northwest Pacific Ocean. It borders the Sea of Japan to the west, and extends from the Sea of Okhotsk in the north to the East China Sea
maybe we can use a nested array or an array of tuples to store each location's coordinates and text at the same time?

const locationWindows = [[lon, lan, text]]

2020-06-24 16:36 UTC, tjncgit commented on portfolio/src/main/java/com/google/sps/servlets/LoginStatus.java
>              boolean statusBool = userLoginBool.get(userEmail);
are you talking about the statusbool

2020-06-25 20:53 UTC, Howon approved these changes

2020-06-25 20:53 UTC, Howon commented
Good work! :)

2020-06-25 20:53 UTC, merged